Update build

diff --git a/.openshift/action_hooks/build b/.openshift/action_hooks/build
--- a/.openshift/action_hooks/build
+++ b/.openshift/action_hooks/build
@@ -31,41 +31,41 @@ if [ ! -x ${OPENSHIFT_DATA_DIR}bin/pip3 ]; then
 fi
 
 ### INSTALL BLAS ###
-if [ ! -f "${OPENSHIFT_DATA_DIR}lib/libfblas.a" ]; then
-    cd ${OPENSHIFT_TMP_DIR}
-    wget http://www.netlib.org/blas/blas.tgz
-    tar xzf blas.tgz
-    cd BLAS-*/
-    gfortran -O3 -m64 -fPIC -c *.f
-    ar r libfblas.a *.o
-    ranlib libfblas.a
-    gfortran -O3 -m64 -fPIC -shared *.f -o libfblas.so
-    [ "$?" != 0 ] && exit 1
-    cp -f libfblas.a ${OPENSHIFT_DATA_DIR}lib/
-    cp -f libfblas.so ${OPENSHIFT_DATA_DIR}lib/
-
-    ### CLEANUP ###
-    cd ${OPENSHIFT_TMP_DIR}
-    rm -rf ${OPENSHIFT_TMP_DIR}/*
-fi
+#if [ ! -f "${OPENSHIFT_DATA_DIR}lib/libfblas.a" ]; then
+#    cd ${OPENSHIFT_TMP_DIR}
+#    wget http://www.netlib.org/blas/blas.tgz
+#    tar xzf blas.tgz
+#    cd BLAS-*/
+#    gfortran -O3 -m64 -fPIC -c *.f
+#    ar r libfblas.a *.o
+#    ranlib libfblas.a
+#    gfortran -O3 -m64 -fPIC -shared *.f -o libfblas.so
+#    [ "$?" != 0 ] && exit 1
+#    cp -f libfblas.a ${OPENSHIFT_DATA_DIR}lib/
+#    cp -f libfblas.so ${OPENSHIFT_DATA_DIR}lib/
+#
+#    ### CLEANUP ###
+#    cd ${OPENSHIFT_TMP_DIR}
+#    rm -rf ${OPENSHIFT_TMP_DIR}/*
+#fi
 
 ### INSTALL LAPACK ###
-if [ ! -f "${OPENSHIFT_DATA_DIR}lib/liblapack.a" ]; then
-    cd ${OPENSHIFT_TMP_DIR}
-    wget http://www.netlib.org/lapack/lapack.tgz
-    tar xzf lapack.tgz
-    cd lapack-*/
-    cp INSTALL/make.inc.gfortran make.inc
-    sed -i -e 's/^OPTS .*$/OPTS = -O2 -frecursive -m64 -fPIC/' make.inc
-    sed -i -e 's/^NOOPT .*$/NOOPT = -O0 -frecursive -m64 -fPIC/' make.inc
-    make lapacklib
-    [ "$?" != 0 ] && exit 1
-    cp liblapack.a ${OPENSHIFT_DATA_DIR}lib/
-
-    ### CLEANUP ###
-    cd ${OPENSHIFT_TMP_DIR}
-    rm -rf ${OPENSHIFT_TMP_DIR}/*
-fi
+#if [ ! -f "${OPENSHIFT_DATA_DIR}lib/liblapack.a" ]; then
+#    cd ${OPENSHIFT_TMP_DIR}
+#    wget http://www.netlib.org/lapack/lapack.tgz
+#    tar xzf lapack.tgz
+#    cd lapack-*/
+#    cp INSTALL/make.inc.gfortran make.inc
+#    sed -i -e 's/^OPTS .*$/OPTS = -O2 -frecursive -m64 -fPIC/' make.inc
+#    sed -i -e 's/^NOOPT .*$/NOOPT = -O0 -frecursive -m64 -fPIC/' make.inc
+#    make lapacklib
+#    [ "$?" != 0 ] && exit 1
+#    cp liblapack.a ${OPENSHIFT_DATA_DIR}lib/
+#
+#    ### CLEANUP ###
+#    cd ${OPENSHIFT_TMP_DIR}
+#    rm -rf ${OPENSHIFT_TMP_DIR}/*
+#fi
 
 ### INSTALL NUMPY/SCIPY/MATPLOTLIB ###
 export BLAS=${OPENSHIFT_DATA_DIR}lib/libfblas.a
