Update build

diff --git a/.openshift/action_hooks/build b/.openshift/action_hooks/build
--- a/.openshift/action_hooks/build
+++ b/.openshift/action_hooks/build
@@ -30,6 +30,24 @@ if [ ! -x ${OPENSHIFT_DATA_DIR}bin/pip3 ]; then
     rm -rf ${OPENSHIFT_TMP_DIR}/*
 fi
 
+### INSTALL R ###
+if [ ! -x ${OPENSHIFT_DATA_DIR}bin/R ]; then
+    cd ${OPENSHIFT_TMP_DIR}
+    wget http://cran.cnr.berkeley.edu/src/base/R-3/R-3.2.5.tar.gz
+    tar xzf R-3.2.5.tar.gz
+    cd R-3.2.5
+    ./configure --prefix=${OPENSHIFT_DATA_DIR} --with-recommended-packages=no --with-system-zlib=no --enable-java=on
+    make
+    [ "$?" != 0 ] && exit 1
+
+    make install
+    [ "$?" != 0 ] && exit 1
+
+    ### CLEANUP ###
+    cd ${OPENSHIFT_TMP_DIR}
+    rm -rf ${OPENSHIFT_TMP_DIR}/*
+fi
+
 ### INSTALL BLAS ###
 #if [ ! -f "${OPENSHIFT_DATA_DIR}lib/libfblas.a" ]; then
 #    cd ${OPENSHIFT_TMP_DIR}
